// Generated by npm run images:portraits. Edit crop centers in scripts/gallery-portrait-crops.json.
export const GALLERY_PORTRAITS: Record<string, string> = {
  "/stack-lamp/stack-lamp-blue-lifestyle.png": "/gallery-portraits/stack-lamp--stack-lamp-blue-lifestyle.jpg",
  "/stack-lamp/stack-lamp-orange-lifestyle-1.png": "/gallery-portraits/stack-lamp--stack-lamp-orange-lifestyle-1.jpg",
  "/stack-lamp/stack-lamp-orange-lifestyle.png": "/gallery-portraits/stack-lamp--stack-lamp-orange-lifestyle.jpg",
  "/flute-lamp/flute-matcha-lifestyle-shot.png": "/gallery-portraits/flute-lamp--flute-matcha-lifestyle-shot.jpg",
  "/flute-lamp/flute-matcha-lifestyle-shot-dark.png": "/gallery-portraits/flute-lamp--flute-matcha-lifestyle-shot-dark.jpg",
  "/flute-lamp/flute-red-lifestyle.png": "/gallery-portraits/flute-lamp--flute-red-lifestyle.jpg",
  "/flute-lamp/flute-red-close-up.png": "/gallery-portraits/flute-lamp--flute-red-close-up.jpg",
  "/flute-lamp/flute-clear-interaction-shot-dark.png": "/gallery-portraits/flute-lamp--flute-clear-interaction-shot-dark.jpg",
  "/flute-lamp/flute-clear-lifestyle-shot-dark-3.png": "/gallery-portraits/flute-lamp--flute-clear-lifestyle-shot-dark-3.jpg",
  "/flute-lamp/flute-clear-lifestyle-shot-dark-4.png": "/gallery-portraits/flute-lamp--flute-clear-lifestyle-shot-dark-4.jpg",
  "/flute-lamp/flute-clear-lifestyle-shot-dark-2.png": "/gallery-portraits/flute-lamp--flute-clear-lifestyle-shot-dark-2.jpg",
  "/flute-lamp/flute-clear-lifestyle-shot-dark-1.png": "/gallery-portraits/flute-lamp--flute-clear-lifestyle-shot-dark-1.jpg",
  "/flute-lamp/flute-clear-lifestyle-shot-dark.png": "/gallery-portraits/flute-lamp--flute-clear-lifestyle-shot-dark.jpg",
  "/pearl-lamp/pearl-lamp-red-lifestyle.png": "/gallery-portraits/pearl-lamp--pearl-lamp-red-lifestyle.jpg",
  "/pearl-lamp/pearl-lamp-green-lifestyle.png": "/gallery-portraits/pearl-lamp--pearl-lamp-green-lifestyle.jpg",
  "/mushroom-lamp/kasane-lamp-black-lifestyle-shot.png": "/gallery-portraits/mushroom-lamp--kasane-lamp-black-lifestyle-shot.jpg",
  "/mushroom-lamp/kasane-lamp-black-interaction-shot.png": "/gallery-portraits/mushroom-lamp--kasane-lamp-black-interaction-shot.jpg",
  "/mushroom-lamp/kasane-lamp-black-detail-shot.png": "/gallery-portraits/mushroom-lamp--kasane-lamp-black-detail-shot.jpg"
};
